SET IDENTITY_INSERT [dbo].[Cars] ON
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (1, N'Nissan', N'None', N'Skyline GT-R R34', 1999, 120000, 2, 2, 65000, 3, N'None', N'Bayside Blue', N'JN1BN34D7X0000001', N'The legendary Nissan Skyline GT-R R34, known for its RB26DETT engine and AWD performance.', 0, N'2025-03-23 21:04:29', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (2, N'Porsche', N'None', N'911 Turbo S BRABUS', 2023, 280000, 2, 1, 3200, 3, N'None', N'Jet Black', N'WP0AD2A99KS000002', N'A high-performance Porsche 911 Turbo S, modified by BRABUS for extreme speed and luxury.', 0, N'2025-03-23 21:07:30', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (3, N'McLaren', N'None', N'720S', 2021, 310000, 2, 1, 12000, 3, N'None', N'Onyx Black', N'SBM14DCA6LW000003', N'The McLaren 720S, a supercar that blends aerodynamics with blistering speed.', 0, N'2025-03-23 21:10:38', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (4, N'Lamborghini', N'None', N'Aventador SVJ', 2022, 650000, 2, 1, 8000, 3, N'None', N'Rosso Mars', N'ZHWUM6ZD9ML000004', N'A track-focused beast, the Lamborghini Aventador SVJ dominates roads and circuits alike.', 0, N'2025-03-23 21:12:22', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (5, N'Ferrari', N'None', N'F8 Tributo', 2021, 290000, 2, 1, 9500, 3, N'None', N'Rosso Corsa', N'ZFF92LLA5L0000005', N'The Ferrari F8 Tributo, an engineering marvel with a V8 powerhouse.', 0, N'2025-03-23 21:13:03', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (6, N'Bugatti', N'None', N'Chiron Super Sport', 2022, 3900000, 2, 1, 2000, 3, N'None', N'Nocturne Black', N'VF9SW2600LM000006', N'The Bugatti Chiron Super Sport, pushing the boundaries of hypercar engineering.', 0, N'2025-03-23 21:13:26', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (7, N'Mercedes-Benz', N'None', N'AMG GT Black Series', 2021, 325000, 2, 1, 7800, 3, N'None', N'Obsidian Black', N'W1K1904791M000007', N'The Mercedes-AMG GT Black Series, an ultimate track-oriented machine with a powerful twin-turbo V8.', 0, N'2025-03-23 21:13:48', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (8, N'Tesla', N'None', N'Model S Plaid', 2023, 135000, 3, 1, 5000, 2, N'None', N'Pearl White', N'5YJSA1E49MF000008', N'The Tesla Model S Plaid, redefining electric speed with its tri-motor setup.', 0, N'2025-03-23 21:14:23', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (9, N'Rolls-Royce', N'None', N'Wraith Black Badge', 2022, 400000, 2, 1, 6500, 3, N'None', N'Diamond Black', N'SCA665C50KU000009', N'A Rolls-Royce Wraith Black Badge, the pinnacle of bespoke luxury and power.', 0, N'2025-03-23 21:14:43', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (10, N'Chevrolet', N'None', N'Corvette C8 Z06', 2023, 120000, 2, 1, 3000, 3, N'None', N'Torch Red', N'1G1YY12S2P000010', N'The Chevrolet Corvette C8 Z06, a mid-engine American supercar with exotic-level performance.', 0, N'2025-03-23 21:14:58', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (11, N'Mercedes-Benz', N'None', N'SEC 500', 1991, 65000, 2, 2, 98000, 3, N'None', N'Black', N'WDB1260441A000001', N'The Mercedes-Benz SEC 500, a classic grand tourer with a powerful V8 engine.', 0, N'2025-03-23 22:08:31', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (12, N'Audi', N'None', N'RS6 Avant', 2023, 130000, 2, 1, 8500, 2, N'None', N'Gray', N'WUAPCBF23PN000002', N'The Audi RS6 Avant, a high-performance wagon with a twin-turbo V8 and Quattro AWD.', 0, N'2025-03-23 22:09:04', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (13, N'Mercedes-Maybach', N'None', N'S 680', 2023, 230000, 2, 1, 5000, 2, N'None', N'Black', N'W1K6X7GB0PA000003', N'The Mercedes-Maybach S 680, the pinnacle of luxury with a V12 powertrain.', 0, N'2025-03-23 22:09:28', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (14, N'Mercedes-Benz', N'None', N'S63 AMG E Performance', 2024, 180000, 2, 1, 2500, 2, N'None', N'Obsidian Black', N'W1K6G7CB0PA000004', N'The latest Mercedes-Benz S63 AMG, featuring a hybrid-assisted twin-turbo V8 with over 800 HP.', 0, N'2025-03-23 22:09:43', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (15, N'BMW', N'None', N'M4 G82', 2023, 100000, 2, 1, 7500, 3, N'None', N'Light Green', N'WBS33AZ03PC000005', N'The BMW M4 G82, a high-performance coupe with a twin-turbo inline-6 and aggressive styling.', 0, N'2025-03-23 22:09:56', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (16, N'Porsche', N'None', N'911 GT3 RS', 2023, 250000, 2, 2, 4000, 3, N'None', N'Black', N'WP0AF2A94PS000006', N'The Porsche 911 GT3 RS, an aerodynamically enhanced track monster with a naturally aspirated flat-six.', 0, N'2025-03-23 22:10:08', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (17, N'Bentley', N'None', N'Mansory Continental GT', 2023, 400000, 2, 1, 3000, 3, N'None', N'Dark Green', N'SCBCB2ZG4PC000007', N'The Bentley Mansory Continental GT, an ultra-luxury coupe with bespoke craftsmanship and performance.', 0, N'2025-03-23 22:10:20', 1, NULL, NULL, NULL, NULL, 1)
INSERT INTO [dbo].[Cars] ([Id], [Brand], [BrandImagePath], [Model], [Year], [Price], [Fuel], [Transmission], [Miles], [Body], [BodyTypeImage], [Color], [VIN], [Text], [IsDeleted], [CreatedDate], [CreatedBy], [UpdatedDate], [UpdatedBy], [DeletedDate], [DeletedBy], [UserId]) VALUES (18, N'Nissan', N'None', N'GT-R R35', 2023, 115000, 2, 1, 9200, 3, N'None', N'Gray', N'JN1AR5EF4PM000008', N'The Nissan GT-R R35, an AWD twin-turbo V6 powerhouse with legendary performance.', 0, N'2025-03-23 22:10:35', 1, NULL, NULL, NULL, NULL, 1)
SET IDENTITY_INSERT [dbo].[Cars] OFF

--------------------------------------

SET IDENTITY_INSERT [dbo].[CarImage] ON
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (1, 1, N'https://cdn.bhdw.net/im/black-nissan-skyline-r-34-gtr-under-the-rain-wallpaper-81888_w635.webp')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (2, 2, N'https://carrosbemmontados.com.br/wp-content/uploads/2023/09/Porsche-carros.png.webp
')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (3, 3, N'https://www.exoticshunter.com/imagetag/377/main/l/Used-2017-McLaren-570S-Wrapped-Matte-Black-Novitec-1016-Carbon-Larini-Exhaust-Front-Lift-1680805937.jpg
')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (4, 4, N'https://bringatrailer.com/wp-content/uploads/2023/01/2022_lamborghini_aventador-ultimae_black-85534.jpg?fit=940%2C627')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (5, 5, N'https://spots.ag/2024/05/22/ferrari-f8-tributo-c506222052024033822_1.jpg?1716341935')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (6, 6, N'https://exclusivecarregistry.com/render-images?imgid=115326')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (7, 7, N'https://f1rstmotors.com/_next/image?url=https%3A%2F%2Ff1rst-motors.s3.me-central-1.amazonaws.com%2Fblog%2F1714669997255-blob&w=3840&q=75')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (8, 8, N'https://unpluggedperformance.com/wp-content/uploads/2025/01/Joe-Rogan-Pearl-White-Tesla-Model-S-Plaid-S-APEX-build-done-by-Unplugged-Performance-1920px-Image-28-1.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (9, 9, N'https://i.redd.it/9r60877l4tz51.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (10, 10, N'https://www.corvetteblogger.com/images/content/2023/020723_16b.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (11, 11, N'https://cdn.rmsothebys.com/5/1/0/6/5/3/510653a95bd2039ff1804586cec03419160a2238.webp')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (12, 12, N'https://assets.nexuspointapex.co.uk/resize/1024/tenant_d9013b5a-4990-4f3e-beec-4e1fc85990eb/media/7472825/WUAZZZF20SN906507_1.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (13, 13, N'https://www.goldcoastautogallery.com/galleria_images/11388/11388_p2_l.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (14, 14, N'https://img.cdn.dragon2000.net/C3927/U141/IMG_5660-large.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (15, 15, N'https://brixtonforged.com/wp-content/uploads/2022/10/brixton-forged-adro-green-bmw-g82-cm5-rs-9.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (16, 16, N'https://www.chicagomotorcars.com/imagetag/11513/main/l/Used-2024-Porsche-911-GT3-RS-Weissach!-Full-Body-PPF!-Front-End-Lifter!-Sinister-Spec!-Loaded!-1707950268.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (17, 17, N'https://s1.cdn.autoevolution.com/images/news/mansory-bentley-flying-spur-is-green-with-envy-at-the-stock-model-for-being-prettier-183328_1.jpg')
INSERT INTO [dbo].[CarImage] ([Id], [CarId], [ImagePath]) VALUES (18, 18, N'https://i.postimg.cc/8zMGkvd3/Screenshot-2025-03-23-223357.png')
SET IDENTITY_INSERT [dbo].[CarImage] OFF
